In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

import warnings

In [2]:
train = pd.read_csv('C:\\Users\\guilh_000\Documents\\tweetsclassify\\train.csv', encoding='latin-1')

print(train.shape)

(99989, 3)


In [3]:
pd.options.display.max_colwidth = 100
train.head(10)

ItemID  Sentiment  \
0       1          0   
1       2          0   
2       3          1   
3       4          0   
4       5          0   
5       6          0   
6       7          1   
7       8          0   
8       9          1   
9      10          1   

                                                                                         SentimentText  
0                                                             is so sad for my APL friend.............  
1                                                                     I missed the New Moon trailer...  
2                                                                              omg its already 7:30 :O  
3            .. Omgaga. Im sooo  im gunna CRy. I've been at this dentist since 11.. I was suposed 2...  
4                                                         i think mi bf is cheating on me!!!       T_T  
5                                                                    or i just worry too much?          
6                                                                   Juuuuuuuuuuuuuuuuussssst Chillin!!  
7                                               Sunny Again        Work Tomorrow  :-|       TV Tonight  
8                                                      handed in my uniform today . i miss you already  
9                                                             hmmmm.... i wonder how she my number @-)

In [9]:
import string
import re
 
from nltk.corpus import stopwords 
stopwords_english = stopwords.words('english')

additional_stop_words = ['rt','via','...','http','twitpic','tinyurl','www', 'amp']
stopwords_list = stopwords_english + additional_stop_words
 
from nltk.stem import PorterStemmer
stemmer = PorterStemmer()
 
from nltk.tokenize import TweetTokenizer
 
# Happy Emoticons
emoticons_happy = set([
    ':-)', ':)', ';)', ':o)', ':]', ':3', ':c)', ':>', '=]', '8)', '=)', ':}',
    ':^)', ':-D', ':D', '8-D', '8D', 'x-D', 'xD', 'X-D', 'XD', '=-D', '=D',
    '=-3', '=3', ':-))', ":'-)", ":')", ':*', ':^*', '>:P', ':-P', ':P', 'X-P',
    'x-p', 'xp', 'XP', ':-p', ':p', '=p', ':-b', ':b', '>:)', '>;)', '>:-)',
    '<3'
    ])
 
# Sad Emoticons
emoticons_sad = set([
    ':L', ':-/', '>:/', ':S', '>:[', ':@', ':-(', ':[', ':-||', '=L', ':<',
    ':-[', ':-<', '=\\', '=/', '>:(', ':(', '>.<', ":'-(", ":'(", ':\\', ':-c',
    ':c', ':{', '>:\\', ';('
    ])
 
# all emoticons (happy + sad)
emoticons = emoticons_happy.union(emoticons_sad)
 
def clean_tweets(tweet):
    # remove stock market tickers like $GE
    tweet = re.sub(r'\$\w*', '', tweet)
 
    # remove old style retweet text "RT"
    tweet = re.sub(r'^RT[\s]+', '', tweet)
    
    #remove mentions and usernames
    tweet = re.sub("(@[A-Za-z0-9]+)", " ", tweet)
 
    # remove hyperlinks
    tweet = re.sub(r'https?:\/\/.*[\r\n]*', '', tweet)
    
    # remove hashtags
    # only removing the hash # sign from the word
    tweet = re.sub(r'#', '', tweet)
    
    tweet= re.sub("[^a-zA-Z]", " ", tweet)
 
    # tokenize tweets
    tokenizer = TweetTokenizer(preserve_case=False, strip_handles=True, reduce_len=True)
    tweet_tokens = tokenizer.tokenize(tweet)
 
    tweets_clean = []    
    for word in tweet_tokens:
        if (word not in stopwords_list and # remove stopwords
              word not in emoticons and # remove emoticons
                word not in string.punctuation): # remove punctuation
            #tweets_clean.append(word)
            stem_word = stemmer.stem(word) # stemming word
            tweets_clean.append(stem_word)
 
    return tweets_clean

In [10]:
train['normalized'] = train.SentimentText.apply(clean_tweets)
train['normal'] = [' '.join(map(str, l)) for l in train['normalized']]

In [11]:
train.head()

ItemID  Sentiment  \
0       1          0   
1       2          0   
2       3          1   
3       4          0   
4       5          0   

                                                                                         SentimentText  \
0                                                             is so sad for my APL friend.............   
1                                                                     I missed the New Moon trailer...   
2                                                                              omg its already 7:30 :O   
3            .. Omgaga. Im sooo  im gunna CRy. I've been at this dentist since 11.. I was suposed 2...   
4                                                         i think mi bf is cheating on me!!!       T_T   

                                                                       normalized  \
0                                                              [sad, apl, friend]   
1                                                      [miss, new, moon, trailer]   
2                                                                  [omg, alreadi]   
3  [omgaga, im, sooo, im, gunna, cri, dentist, sinc, supos, get, crown, put, min]   
4                                                          [think, mi, bf, cheat]   

                                                             normal  
0                                                    sad apl friend  
1                                             miss new moon trailer  
2                                                       omg alreadi  
3  omgaga im sooo im gunna cri dentist sinc supos get crown put min  
4                                                 think mi bf cheat

In [12]:
train.tail(20)

ItemID  Sentiment  \
99969   99981          0   
99970   99982          0   
99971   99983          0   
99972   99984          1   
99973   99985          1   
99974   99986          0   
99975   99987          0   
99976   99988          1   
99977   99989          1   
99978   99990          1   
99979   99991          1   
99980   99992          1   
99981   99993          0   
99982   99994          1   
99983   99995          0   
99984   99996          0   
99985   99997          1   
99986   99998          0   
99987   99999          1   
99988  100000          1   

                                                                                             SentimentText  \
99969                                                                                   @CTerry1985  Sorry   
99970                                                                  @CTerry1985 damn it, dont have sky    
99971       @CTerry1985 That's the thing; the new raft of Star Wars films were just a raft of #EpicFail s    
99972                                                                                            @cthagod    
99973                                                                                @ctham  #FollowFriday   
99974  @ctham #awaresg You are not wrong. But from a my own male point of view, I felt excluded (even w...   
99975                                         @ctham @mommyfizz cuz you big burly man.  hahahahahahahahaha   
99976  @ctham @Wilsurn Trying to get a wider range of shirts to suit everyone. Please make requests if ...   
99977                                                      @ctham Haha I love the passion in your support    
99978  @cthulhullahoop That sucks...I like living in Coopersville, I don't need no special bags or anyt...   
99979                                         @cunningstunts till i can go home been here till saturday  x   
99980                                                           @cunningstunts22 afternoon jim hows you  x   
99981      @cup_a_tea The foot is really bad. Like the worst it's ever been. I can barely walk right now.    
99982            @Cup_Of_Katy Have fun doing health &amp; safety :S Just switch off and look spritely  XXX   
99983  @cupati It took me waaay too long to get your message about being ashamed...right now I really a...   
99984                       @Cupcake  seems like a repeating problem   hope you're able to find something.   
99985  @cupcake__ arrrr we both replied to each other over different tweets at the same time  , i'll se...   
99986                                                                       @CuPcAkE_2120 ya i thought so    
99987                                        @Cupcake_Dollie Yes. Yes. I'm glad you had more fun with me.    
99988                                                                      @cupcake_kayla haha yes you do    

                                                                               normalized  \
99969                                                                             [sorri]   
99970                                                                   [damn, dont, sky]   
99971                                 [thing, new, raft, star, war, film, raft, epicfail]   
99972                                                                                  []   
99973                                                                      [followfriday]   
99974         [awaresg, wrong, male, point, view, felt, exclud, even, non, repli, thread]   
99975                                          [cuz, big, burli, man, hahahahahahahahaha]   
99976  [tri, get, wider, rang, shirt, suit, everyon, pleas, make, request, need, awaresg]   
99977                                                      [haha, love, passion, support]   
99978                           [suck, like, live, coopersvil, need, special, bag, anyth]   
99979                                                 [till, go, home, till, saturda

In [47]:
from scipy.sparse import hstack
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer, TfidfTransformer  

count_vectorizer = CountVectorizer(ngram_range=(1,2))
vectorized_data =count_vectorizer.fit_transform(train['normal'])

tfidfconverter = TfidfTransformer()  
tfid_data = tfidfconverter.fit_transform(vectorized_data)

indexed_data =hstack((np.array(range(0,tfid_data.shape[0]))[:,None],tfid_data))

#vectorizer = TfidfVectorizer(min_df= 3, stop_words="english", sublinear_tf=True, norm='l2', ngram_range=(1, 2))
#final_features = vectorizer.fit_transform(train['normal'])

#indexed_data =hstack((np.array(range(0,vectorized_data.shape[0]))[:,None],vectorized_data))
#indexed_data =hstack((np.array(range(0,final_features.shape[0]))[:,None],final_features))

#vectorized_data.shape
tfid_data.shape
#final_features.shape

(99989, 405288)

In [48]:
targets = train.iloc[:, 1]

from sklearn.model_selection import train_test_split 
data_train, data_test, targets_train, targets_test =train_test_split(indexed_data, targets, test_size=0.2,random_state=100)
data_train_index = data_train[:,0]
data_train = data_train[:,1:]
data_test_index = data_test[:,0]
data_test = data_test[:,1:]

In [15]:
#############################################################################################################
from sklearn.naive_bayes import MultinomialNB
nbc = MultinomialNB(fit_prior=True, alpha=1.0).fit(data_train, targets_train)

In [16]:
from sklearn.metrics import accuracy_score, confusion_matrix, precision_recall_fscore_support, classification_report

nb_pred = nbc.predict(data_test)

print(confusion_matrix(targets_test, nb_pred))
print(classification_report(targets_test,nb_pred))
print(accuracy_score(targets_test, nb_pred))

[[5875 2806]
 [2464 8853]]
              precision    recall  f1-score   support

           0       0.70      0.68      0.69      8681
           1       0.76      0.78      0.77     11317

    accuracy                           0.74     19998
   macro avg       0.73      0.73      0.73     19998
weighted avg       0.74      0.74      0.74     19998

0.7364736473647365


In [17]:
########################################linear svm
from sklearn.svm import LinearSVC
lsvm= LinearSVC(C=1.0)
lsvm.fit(data_train, targets_train)

C:\Users\guilh_000\Anaconda3\lib\site-packages\sklearn\svm\_base.py:977: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


LinearSVC()

In [18]:
targets_pred = lsvm.predict(data_test)

print(confusion_matrix(targets_test, targets_pred))
print(classification_report(targets_test,targets_pred))
print(accuracy_score(targets_test, targets_pred))

[[5730 2951]
 [2390 8927]]
              precision    recall  f1-score   support

           0       0.71      0.66      0.68      8681
           1       0.75      0.79      0.77     11317

    accuracy                           0.73     19998
   macro avg       0.73      0.72      0.73     19998
weighted avg       0.73      0.73      0.73     19998

0.7329232923292329


In [19]:
#########################################################
from sklearn.linear_model import LogisticRegression
lrc = LogisticRegression(random_state=0)
lrc.fit(data_train, targets_train)

C:\Users\guilh_000\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(random_state=0)

In [20]:
targets_pred = lrc.predict(data_test)

print(confusion_matrix(targets_test, targets_pred))
print(classification_report(targets_test,targets_pred))
print(accuracy_score(targets_test, targets_pred))

[[5682 2999]
 [2009 9308]]
              precision    recall  f1-score   support

           0       0.74      0.65      0.69      8681
           1       0.76      0.82      0.79     11317

    accuracy                           0.75     19998
   macro avg       0.75      0.74      0.74     19998
weighted avg       0.75      0.75      0.75     19998

0.7495749574957495


In [21]:
###################################################################################
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=100, random_state=0, max_depth=100)
rfc.fit(data_train, targets_train)

RandomForestClassifier(max_depth=100, random_state=0)

In [22]:
rfy_pred = rfc.predict(data_test)

print(confusion_matrix(targets_test, rfy_pred))
print(classification_report(targets_test, rfy_pred))
print(accuracy_score(targets_test, rfy_pred))

[[ 2370  6311]
 [  372 10945]]
              precision    recall  f1-score   support

           0       0.86      0.27      0.41      8681
           1       0.63      0.97      0.77     11317

    accuracy                           0.67     19998
   macro avg       0.75      0.62      0.59     19998
weighted avg       0.73      0.67      0.61     19998

0.6658165816581658


In [24]:
from sklearn.model_selection import GridSearchCV

hiperparameters = {'C': (0.01,0.1,1.0,10.0,100.0)}
grid = GridSearchCV(LogisticRegression(), hiperparameters, cv=3)
grid.fit(data_train, targets_train)

print(grid.best_params_)
print(grid.best_score_)

C:\Users\guilh_000\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
C:\Users\guilh_000\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logi

{'C': 1.0}
0.7461089834370678


C:\Users\guilh_000\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [25]:
hiperparameters = {'alpha': (1.0,1.5,2.0,2.5,3.0),'fit_prior':[True, False]}
grid = GridSearchCV(MultinomialNB(), hiperparameters, cv=3)
grid.fit(data_train, targets_train)

print(grid.best_params_)
print(grid.best_score_)

{'alpha': 2.0, 'fit_prior': True}
0.7392831977193143


In [34]:
nb = MultinomialNB(fit_prior=True, alpha=2.0).fit(data_train, targets_train)

In [35]:
nb_pred = nb.predict(data_test)

print(confusion_matrix(targets_test, nb_pred))
print(classification_report(targets_test,nb_pred))
print(accuracy_score(targets_test, nb_pred))

[[5472 3209]
 [1959 9358]]
              precision    recall  f1-score   support

           0       0.74      0.63      0.68      8681
           1       0.74      0.83      0.78     11317

    accuracy                           0.74     19998
   macro avg       0.74      0.73      0.73     19998
weighted avg       0.74      0.74      0.74     19998

0.7415741574157416


In [36]:
hiperparameters = {'C': (0.01,0.1,1.0,5.0,10.0)}
grid = GridSearchCV(LinearSVC(), hiperparameters, cv=3)
grid.fit(data_train, targets_train)

print(grid.best_params_)
print(grid.best_score_)

C:\Users\guilh_000\Anaconda3\lib\site-packages\sklearn\svm\_base.py:977: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Users\guilh_000\Anaconda3\lib\site-packages\sklearn\svm\_base.py:977: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Users\guilh_000\Anaconda3\lib\site-packages\sklearn\svm\_base.py:977: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Users\guilh_000\Anaconda3\lib\site-packages\sklearn\svm\_base.py:977: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)
C:\Users\guilh_000\Anaconda3\lib\site-packages\sklearn\svm\_base.py:977: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the

{'C': 0.1}
0.7446713293577417


C:\Users\guilh_000\Anaconda3\lib\site-packages\sklearn\svm\_base.py:977: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


In [37]:
lsvc= LinearSVC(C=0.1)
lsvc.fit(data_train, targets_train)

C:\Users\guilh_000\Anaconda3\lib\site-packages\sklearn\svm\_base.py:977: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


LinearSVC(C=0.1)

In [38]:
targets_pred = lsvc.predict(data_test)

print(confusion_matrix(targets_test, targets_pred))
print(classification_report(targets_test,targets_pred))
print(accuracy_score(targets_test, targets_pred))

[[5596 3085]
 [1992 9325]]
              precision    recall  f1-score   support

           0       0.74      0.64      0.69      8681
           1       0.75      0.82      0.79     11317

    accuracy                           0.75     19998
   macro avg       0.74      0.73      0.74     19998
weighted avg       0.75      0.75      0.74     19998

0.7461246124612462


In [39]:
##Linear regression wins
######################################################### test model with new data
test = pd.read_csv('C:\\Users\\guilh_000\\Documents\\tweetsclassify\\testing.csv')
test.shape

(21, 3)

In [41]:
test['normalized'] = test.Text.apply(clean_tweets)
test['normal'] = [' '.join(map(str, l)) for l in test['normalized']]

In [42]:
test.head(10)

TweetID  \
0        1   
1        2   
2        3   
3        4   
4        5   
5        6   
6        7   
7        8   
8        9   
9       10   

                                                                                                  Text  \
0                                                                           I am feeling so depressed    
1                                                                      I'm so sad. i can't stop crying   
2                                                                             I don't feel good at all   
3                                                                              I dont feel good at all   
4                                                                                  I'm feeling so good   
5  If I just breath now And close my eyes Maybe it'll go away #depression #mentalhealth #MentalHeal...   
6  I am not sad I'm depressed all of a sudden I get this urge feeling of sadness I hope I can stop ...   
7                                                I got the job I wanted. I'm really happy right now :)   
8                                                                      Holidays can't come soon enough   
9                    My anxiety has been extremely bad lately. If you are suffering, you are not alone   

   Label  \
0      0   
1      0   
2      0   
3      0   
4      1   
5      0   
6      0   
7      1   
8      1   
9      0   

                                                                                            normalized  \
0                                                                                      [feel, depress]   
1                                                                                     [sad, stop, cri]   
2                                                                                         [feel, good]   
3                                                                                   [dont, feel, good]   
4                                                                                         [feel, good]   
5                        [breath, close, eye, mayb, go, away, depress, mentalhealth, mentalhealthawar]   
6  [sad, depress, sudden, get, urg, feel, sad, hope, stop, believ, fuckin, loop, trap, deep, depres...   
7                                                               [got, job, want, realli, happi, right]   
8                                                                        [holiday, come, soon, enough]   
9                                                           [anxieti, extrem, bad, late, suffer, alon]   

                                                                                        normal  
0                                                                                 feel depress  
1                                                                                 sad stop cri  
2                                                                                    feel good  
3                                                                               dont feel good  
4                                                                                    feel good  
5                          breath close eye mayb go away depress mentalhealth mentalhealthawar  
6  sad depress sudden get urg feel sad hope stop believ fuckin loop trap deep depress sad help  
7                                                              got job want realli happi right  
8                                                                     holiday come soon enough  
9                                                          anxieti extrem bad late suffer alon

In [43]:
tweet_to_predict = test['normal']
x = count_vectorizer.transform(tweet_to_predict)

In [44]:
test['Prediction'] = lrc.predict(x)

In [45]:
test

TweetID  \
0         1   
1         2   
2         3   
3         4   
4         5   
5         6   
6         7   
7         8   
8         9   
9        10   
10       11   
11       12   
12       13   
13       14   
14       15   
15       16   
16       17   
17       18   
18       19   
19       20   
20       21   

                                                                                                   Text  \
0                                                                            I am feeling so depressed    
1                                                                       I'm so sad. i can't stop crying   
2                                                                              I don't feel good at all   
3                                                                               I dont feel good at all   
4                                                                                   I'm feeling so good   
5   If I just breath now And close my eyes Maybe it'll go away #depression #mentalhealth #MentalHeal...   
6   I am not sad I'm depressed all of a sudden I get this urge feeling of sadness I hope I can stop ...   
7                                                 I got the job I wanted. I'm really happy right now :)   
8                                                                       Holidays can't come soon enough   
9                     My anxiety has been extremely bad lately. If you are suffering, you are not alone   
10                                                              Our zoom meeting went really well today   
11                                     Just tried this new corona beer and it's the best thing ever omg   
12                               I hate to say this, but I doubt I'll ever come back to this restaurant   
13                                                           Food was so good and the staff was cordial   
14                                                                      Just ordered a book from Amazon   
15                                                                                      I'm feeling sad   
16                                                                                  I'm not feeling sad   
17                                         I knew you Playing hide-and-seek and Giving me your weekends   
18                               I knew you Your heartbeat on the High Line Once in twenty lifetimes, I   
19                                                      When you are young they assume you know nothing   
20  You heard the rumors from Inez You can't believe a word she says Most times, but this time it wa...   

    Label  \
0       0   
1       0   
2       0   
3       0   
4       1   
5       0   
6       0   
7       1   
8       1   
9       0   
10      1   
11      1   
12      0   
13      1   
14      1   
15      0   
16      1   
17      1   
18      1   
19      0   
20      0   

                                                                                             normalized  \
0                                                                                       [feel, depress]   
1                                                                                      [sad, stop, cri]   
2                                                                                          [feel, good]   
3                                                                                    [dont, feel, good]   
4                                                                                          [feel, good]   
5                         [breath, close, eye, mayb, go, away, depress, mentalhealth, mentalhealthawar]   
6   [sad, depress, sudden, get, urg, feel, sad, hope, stop, believ, fuckin, loop, trap, deep, depres...   
7                                                                [got, job, want, realli, happi, right]   
8                                                                   

In [46]:
print(confusion_matrix(test['Label'], test['Prediction']))
print(classification_report(test['Label'], test['Prediction']))
print(accuracy_score(test['Label'], test['Prediction']))

[[10  1]
 [ 2  8]]
              precision    recall  f1-score   support

           0       0.83      0.91      0.87        11
           1       0.89      0.80      0.84        10

    accuracy                           0.86        21
   macro avg       0.86      0.85      0.86        21
weighted avg       0.86      0.86      0.86        21

0.8571428571428571


In [49]:
#tdif test
lrtdif = LogisticRegression(random_state=0)
lrtdif.fit(data_train, targets_train)

LogisticRegression(random_state=0)

In [50]:
targets_pred = lrtdif.predict(data_test)

print(confusion_matrix(targets_test, targets_pred))
print(classification_report(targets_test,targets_pred))
print(accuracy_score(targets_test, targets_pred))

[[5442 3239]
 [1735 9582]]
              precision    recall  f1-score   support

           0       0.76      0.63      0.69      8681
           1       0.75      0.85      0.79     11317

    accuracy                           0.75     19998
   macro avg       0.75      0.74      0.74     19998
weighted avg       0.75      0.75      0.75     19998

0.7512751275127513


In [ ]:
[[5682 2999]
 [2009 9308]]
              precision    recall  f1-score   support

           0       0.74      0.65      0.69      8681
           1       0.76      0.82      0.79     11317

    accuracy                           0.75     19998
   macro avg       0.75      0.74      0.74     19998
weighted avg       0.75      0.75      0.75     19998

0.7495749574957495